// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Dummy URL only used by `prisma generate` when DATABASE_URL is not set yet.
    url:
      process.env.DATABASE_URL ??
      "sqlserver://localhost:1433;database=build;user=sa;password=build;encrypt=false;trustServerCertificate=true",
  },
});
